server.port=8761
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Eureka Server configuration
eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/


spring.security.user.name=eureka
spring.security.user.password=password

# Zipkin configuration
spring.zipkin.base-url=http://zipkin:9411
management.tracing.sampling.probability=1.0



management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true












