spring.application.name=order-service

spring.datasource.url=jdbc:postgresql://localhost:5432/order
spring.datasource.username=thaituan
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
server.port=8082

#Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
spring.security.user.name=eureka
spring.security.user.password=password

spring.kafka.bootstrap-servers=localhost:9092



spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Actuator, Prometheus Endpoints
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health, prometheus
management.tracing.sampling.probability=1.0

#Resilience4j
#So luong request theo doi
resilience4j.circuitbreaker.instances.inventory-service.sliding-window-size = 5
#Neu 50% request that bai, Circuit Breaker dong
resilience4j.circuitbreaker.instances.inventory-service.failureRateThreshold = 50
#Sau 10s thu mo lai
resilience4j.circuitbreaker.instances.inventory-service.waitDurationInOpenState = 10s
#
resilience4j.circuitbreaker.instances.inventory-service.permittedNumberOfCallsInHalfOpenState = 2
#
resilience4j.circuitbreaker.instances.inventory-service.slowCallDurationThreshold = 2s
#
resilience4j.circuitbreaker.instances.inventory-service.slowCallRateThreshold = 50
#
resilience4j.retry.instances.inventory-service.max-attempts = 3
#
resilience4j.retry.instances.inventory-service.waitDuration = 2s

resilience4j.retry.instances.inventory-service.retryExceptions = org.springframework.web.client.HttpServerErrorException

resilience4j.timelimiter.instances.inventory-service.timeout-duration = 10s



#Resilience4j
#S? l??ng request theo dõi
resilience4j.circuitbreaker.instances.inventory-service.sliding-window-size = 5 
#N?u 50% request th?t b?i, Circuit Breaker ?óng
resilience4j.circuitbreaker.instances.inventory-service.failureRateThreshold = 50
#Sau 10s th? m? l?i
resilience4j.circuitbreaker.instances.inventory-service.waitDurationInOpenState = 10s
# S? request ???c phép th? khi m? l?i
resilience4j.circuitbreaker.instances.inventory-service.permittedNumberOfCallsInHalfOpenState = 2
# N?u call lâu h?n 2s, coi là ch?m
resilience4j.circuitbreaker.instances.inventory-service.slowCallDurationThreshold = 2s
# N?u 50% call ch?m, ?óng Circuit Breaker
resilience4j.circuitbreaker.instances.inventory-service.slowCallRateThreshold = 50
# Th? l?i t?i ?a 3 l?n
resilience4j.retry.instances.inventory-service.max-attempts = 3
# M?i l?n th? l?i cách nhau 2s
resilience4j.retry.instances.inventory-service.waitDuration = 2s

resilience4j.retry.instances.inventory-service.retryExceptions = org.springframework.web.client.HttpServerErrorException

resilience4j.timelimiter.instances.inventory-service.timeout-duration = 10s



